config/routes.rb
Rails.application.routes.draw do

  resources :ordem_producaos do
      get "1/update_produtos_op" => "ordem_producaos#update_produtos_op"
       get '/print/' => "print#ordem_producao_print"

            member do
            get :clone
        end
  end

    
  resources :layouts do
      member do
            get :clone
        end
      end
        
  resources :orcamentos do
      get '/print/' => "print#orcamento_print"
        member do
            get :clone
        end
  end
  resources :pedido_vendas do
      get '/print/' => "print#pedido_venda_print"
        member do
            get :clone
        end
  end
  resources :clientes do
      get '/print/' => "print#cliente_print"
  end
    
   resources :cliente_estoque_minimos

  ActiveAdmin.routes(self)
    devise_for :users
    devise_scope :user do
      authenticated :user do
        root "default#index", as: :authenticated_root
      end
      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end
    
    root 'devise/sessions#new'
    get 'activities/index'
    get "access_denied" => "default#access_denied"
    get "estado/:estado_id/cidades" => "default#update_cidades"
    get "produto/:produto_id/materials" => "default#update_produtos"
    get "estoque/:tipo_id/:cliente_id/:produto_id/materials" => "default#update_materials_op"
    get "cliente/enderecos" => "default#busca_endereco"
    
    get "cliente/:cliente_id/enderecos" => "default#busca_endereco_cliente"

    get "impressora/:impressora_id/configs" => "default#update_impressora_configs"
    get "gerar-venda/:orcamento_id" => "default#gerar_venda"
    get "gerar-op/:pedido_venda_id" => "default#gerar_op"
    get "/feed" => "activities#index", as: :feed
    get "orcamento-item-descricao/:descricao_id" => "default#update_item_descricao"
    
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base

        attr_accessible :nome_fantasia, :razao_social, :cnpj, :inscricao_municipal, :inscricao_estadual, :cliente_faturamento_id, :cliente_status_id, :user_id, :observacao, :notificacao, :cliente_contatos_attributes, :cliente_enderecos_attributes, :cliente_estoque_minimos_attributes

      include Filterable

    scope :status, -> (status) {
        statuses = status.split(',')
        where cliente_status_id: statuses }
    
    scope :vendedor, -> (vendedor) {
        vendedores = vendedor.split(',')
        where user_id: vendedores }
    
        scope :ramo, -> (ramo) {
        ramos = ramo.split(',')
        where cliente_ramo_id: ramos }
    
    
    scope :search_with, -> (search) {where('nome_fantasia LIKE ?', "%#{search}%")  }

    validates_presence_of :nome_fantasia, :cliente_faturamento_id, :cliente_status_id, :user_id

    
    belongs_to :user
    belongs_to :cliente_status
    belongs_to :cliente_ramo
    belongs_to :cliente_faturamento
    has_many :cliente_contatos, :dependent => :destroy
    has_many :cliente_enderecos, :dependent => :destroy
    has_many :cliente_estoque_minimos, :dependent => :destroy
    has_many :pedido_vendas
    has_many :cliente_estoques
    has_many :orcamentos
    
    accepts_nested_attributes_for :cliente_contatos, :reject_if => :all_blank, :allow_destroy => true
    accepts_nested_attributes_for :cliente_enderecos, :reject_if => :all_blank, :allow_destroy => true
    accepts_nested_attributes_for :cliente_estoque_minimos, :reject_if => :all_blank, :allow_destroy => true

    
    include PublicActivity::Model
    tracked :owner => proc {|controller, model| controller.current_user}
      
        
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
    load_and_authorize_resource  
    before_filter :authenticate_user!
    
     def index
        @status = ClienteStatus.all
         @vendedores = User.where(departamento_id: 1)
         @ramos = ClienteRamo.order('name').all
         @clientes = Cliente.filter(params.slice(:status, :vendedor,:ramo, :search_with)).order("nome_fantasia ASC").paginate(:per_page => 50, :page => params[:page])

     end 

    def create  
        create! { collection_url }
        flash[:notice] = 'Cliente adicionado com sucesso!' 
    end
    
    def update  
        update! { edit_cliente_path}
        flash[:notice] = 'Cliente atualizado com sucesso!' 

    end
  
    
    private
   def cliente_params
      params.require(:cliente).permit(:nome_fantasia, :razao_social, :cnpj, :inscricao_municipal, :inscricao_estadual, :cliente_faturamento_id, :cliente_status_id, :user_id, :observacao, :notificacao, :id,
          cliente_contatos_attributes: [:cliente_id, :nome, :email, :telefone, :observacao, :id, :_destroy],
        cliente_enderecos_attributes: [:id, :name, :cliente_id, :cidade_id,:estado_id, :bairro, :rua, :numero, :complemento, :cep, :rota, :forma_entrega_id, :observacao,  :_destroy, :_update, :_create],
        cliente_estoque_minimos_attributes: [:id, :cliente_id, :produto_id, :material_id, :quantidade, :_destroy, :_update, :_create]) 
    end
    


  

end

app/helpers/clientes_helper.rb
module ClientesHelper

end

app/views/clientes/_cliente_contato_fields.html.erb
<div class="nested-fields item">
<div class="col-md-12">    
<div class="pull-right">
<%= link_to_remove_association f  do%>
    <i class="fa fa-minus"></i>
<% end %>
</div>
</div>
    <div class="col-sm-3">
            <%= f.input :nome %>
        </div>
        <div class="col-sm-3">
            <%= f.input :email, input_html:{:type => 'email'}%>
        </div>
        <div class="col-sm-3">
            <%= f.input :telefone, input_html:{:type => 'tel'} %>
        </div>
        <div class="col-sm-3">
            <%= f.input :observacao, :label => 'Identificação', :placeholder => 'Ex. Cargo, setor' %>
        </div>

</div>

app/views/clientes/_cliente_endereco_fields.html.erb
<div class="nested-fields item">
<div class="col-md-12">    
<div class="pull-right">
<%= link_to_remove_association f  do%>
    <i class="fa fa-minus"></i>
<% end %>
</div>
</div>

        <div class="col-sm-3">
            <%= f.input :name, :label => "Título",:placeholder => 'Ex. Entrega, Fatura' , input_html: {id: "name"}%>
        </div>
        <div style="clear:both;"></div>
        
        <div class="col-sm-2">
            <%= f.input :cep, input_html: {class: "cep", onkeyup: "BuscarCep()"}%>
        </div>        
        <div class="col-sm-5">
            <%= f.input :rua, input_html: { class: "logradouro"} %>
        </div>    
        <div class="col-sm-2">
            <%= f.input :numero, :label => 'Número' %>
        </div>
        <div class="col-sm-3">
            <%= f.input :complemento %>
        </div>
        <div class="col-sm-3">
            <%= f.input :bairro, input_html: { class: "bairro"} %>
        </div>
        <div class="col-sm-3">
            <%var = "estado_" + (Random.rand(10...42)).to_s %>
         <%= f.input :estado_id, collection: Estado.all,  label_method: :uf,  input_html: { id: var, class: 'estado', onchange: "DynamicSelect()" }%>  
        </div>
        <div class="col-sm-3">
            <%= f.input :cidade_id, collection: Cidade.where('estado_id =?', f.object.estado_id) || [],input_html: { 
                        class: 'cidade',
                         "data-option-dependent" => true,
                         "data-option-observed" => var,
                         "data-option-url" => "/estado/:estado_id:/cidades.json",
                         "data-option-key-method" => :id,
                         "data-option-value-method" => :name } %>
         </div>

        <div class="col-sm-3">
            <%= f.input :forma_entrega_id,:collection => FormaEntrega.all,:label_method => :name,:value_method => :id,:label => "Forma de Entrega" ,:include_blank => true %>     
        </div>
        <div class="col-sm-3">
            <%= f.label :rota %>
            <%= f.select :rota, Date::DAYNAMES.zip((0..6)),  { :include_blank=>true }, { :class => 'string optional form-control' } %>
        </div>
        <div class="col-sm-6">
            <%= f.input :observacao, :label => 'Observações',:placeholder => 'Ex. A/C, Referencia' %>
        </div>
</div>

app/views/clientes/_cliente_estoque_fields.html.erb
<div class="nested-fields item">
    <table  class="table table-bordered table-hover">
  <thead>
    <tr>
        <th>Produto</th>
        <th>Material</th>
        <th>Saldo</th>
        <th>Mínimo</th>
        <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cliente.cliente_estoques.each do |estoque| %>
        <tr>
            <td><%= estoque.produto.name if estoque.produto%></td>
            <td><%= estoque.material.name if estoque.material %></td>
            <td><%= estoque.saldo %></td>
             <% @cliente.cliente_estoque_minimos.each do |minimo| %>
            <td>
                <%if minimo.produto_id == estoque.produto_id && minimo.material_id ==  estoque.material_id%>
                    <%= minimo.quantidade %>
                <% end %>
            </td>
            <td>
                <%if minimo.produto_id == estoque.produto_id && minimo.material_id ==  estoque.material_id%>
                <%= f.simple_fields_for :cliente_estoque_minimos do |builder| %>
                    <%if builder.object.id == minimo.id%>
                        <%= render partial: 'cliente_estoque_minimo_fields',locals: {:f => builder} %>
                        <a href="#" onclick="OpenModalEstoqueMinimo(); return false;">Editar</a> 
                    <% end %>
                <% end %>
                <% end %>
            </td>
            <% end %>
        </tr>
      <% end %>
  </tbody>
</table>    

</div>

app/views/clientes/_cliente_estoque_minimo_fields.html.erb
<div class="modal fade"
           id="estoque_minimo" tabindex="-1" role="estoque_minimo" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title">Estoque Mínimo</h3>
      </div>
      <div class="modal-body">
          
          <%= f.hidden_field  :produto_id, :value => '1' %>
          <%= f.hidden_field  :material_id, :value => '1' %>
          <%= f.input :quantidade, :label => "Quantidade" %>
      </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-default  btn-flat pull-left" onclick="CloseModal()">Cancelar</button>
        <button type="button" class="btn btn-success btn-flat" onclick="InserirDescricao()">Inserir</button>
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/clientes/_clientes.html.erb
<% if @clientes.size == 0 %>
   <div class="blank_slate_container">
              <span class="blank_slate">
                <span>Não há clientes para serem exibidos</span><br/>
            <small><%=link_to "Clique aqui",  new_cliente_path%> e adicione um novo cliente.</small>
              </span>
            </div> 



<% else %>
    <% @clientes.each do |cliente| %>
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title"> <%= cliente.nome_fantasia %></h3>
                <%if cliente.cliente_status_id == 2 %>
                <span class="label pull-right label-danger"><%= cliente.cliente_status.name if cliente.cliente_status %></span>
               
                 <%elsif cliente.cliente_status_id == 1%>
                <span class="pull-right label label-success"><%= cliente.cliente_status.name if cliente.cliente_status %></span>
                
                 
                 <%else%>
                <span class="pull-right label label-primary"><%= cliente.cliente_status.name if cliente.cliente_status %></span>
            
                <%end%>

            </div>
            <div class="box-body">
                <div class="col-sm-8">

                  <small>Cadastrado em:</small> <%= l(cliente.created_at.to_date) %>  <br/> 
                  <small>Vendedor:</small> <%= cliente.user.name if cliente.user %>  <br/>
               </div>
                <div class="col-sm-2 ">
            
                    </div>
                <div class="col-sm-2 no-padding ">
                      <%=link_to "Editar",  edit_cliente_path(cliente),  :class => "btn btn-block btn-success btn-flat"%>
                
                    </div>


            </div><!-- /.box-body -->
        </div>
    <%end%>


    <%= will_paginate @clientes%>
<%end%>

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente) do |f| %>
<%= render "shared/messages", object: f.object %>
<div class="box box-success">
<div class="box-header">

</div>
<div class="box-body">
            <div class="col-sm-6">
                <%= f.input :nome_fantasia %>
            </div>
            <div class="col-sm-6">
                <%= f.input :razao_social, :label =>"Razão social"  %>
            </div>
            <div class="col-sm-3"> 
                <%= f.input :cnpj, as: :cnpj, :label =>"CNPJ"  %>
            </div>
            <div class="col-sm-3"> 
                <%= f.input :inscricao_municipal, :label =>"Inscrição municipal" %>
            </div> 
            <div class=" col-sm-3">   
                <%= f.input :inscricao_estadual, :label =>"Inscrição estadual" %>
            </div>
            <div class="col-sm-3">                  
                <%=f.association :cliente_faturamento, collection: ClienteFaturamento.where(active: true), :label => "Tipo de Faturamento",:include_blank => false %>
            </div>
            <div class="col-sm-3">
                <%=f.association :cliente_status, collection: ClienteStatus.all, :label => "Status",:include_blank => false %>
            </div>
            <div class="col-sm-3">
                <%=f.association :cliente_ramo, collection: ClienteRamo.all, :label => "Ramo de mercado",:include_blank => false %>
            </div>
            <div class="col-sm-3">  
                <%= f.input :user_id,:collection =>  User.where(departamento_id: 1),:label_method => :name,:value_method => :id,:label => "Vendedor" ,:include_blank => true %>
            </div>
            <div class="col-sm-3"  style="padding-top: 15px;">  
                <%= f.input :notificacao, :label =>"Receber notificações deste cliente" %>
            </div>
     <div class="col-md-12">  
                <%= f.input :observacao, as: :text, :label =>"Observações" %>
            </div>
</div>
</div><!-- /.box-body -->                   
<div class="nav-tabs-custom">
                  <ul class="nav nav-tabs">
                      <li class="active"><a href="#contatos" data-toggle="tab" aria-expanded="true">Contatos</a></li>
                      <li class=""><a href="#enderecos" data-toggle="tab" aria-expanded="false">Endereços</a></li>
                      <li class=""><a href="#estoques" data-toggle="tab" aria-expanded="false">Estoque</a></li>
                      <li class=""><a href="#comentarios" data-toggle="tab" aria-expanded="false">Comentários</a></li>
                 </ul>
                  <div class="tab-content">
                      <div class="tab-pane active" id="contatos">
                          <fieldset id="cliente_contatos">
                              <%= f.simple_fields_for :cliente_contatos do |builder| %>
                              <%= render "cliente_contato_fields", :f => builder %>
                              <% end %>
                              <div class="col-md-12">  
                                  <%= link_to_add_association '+', f, :cliente_contatos,  :class => "btn  btn-success btn-flat" %>
                              </div>
                          </fieldset>
                      </div><!-- /.tab-pane -->
                      <div class="tab-pane" id="enderecos">
                          <fieldset id="cliente_enderecos">
                              <%= f.fields_for  :cliente_enderecos do |builder| %>
                            
                              <%= render "cliente_endereco_fields", :f => builder, :render_options => { :wrapper => 'inline' }  %>
                              <% end %>
                              <div class="col-md-12">  
                                  <%= link_to_add_association '+', f, :cliente_enderecos, :class => "btn  btn-success btn-flat" %>
                              </div>
                          </fieldset>
                      </div><!-- /.tab-pane -->
                      <div class="tab-pane" id="estoques">
                          <div id="cliente_estoques">
                            <%= render "cliente_estoque_fields", :f => f %>
                          </div>
                      </div><!-- /.tab-pane -->
                  </div><!-- /.tab-content -->
              </div> 

<div class="actions-bar row">
        <% if can? :update, @cliente %>
        <div class="col-md-2 col-xs-6 pull-right">
            <%= f.submit "Salvar", class:"btn btn-block btn-success btn-flat", :onclick => 'SubmitAndRemoveMask()' %>
        </div>
    <% end %>
    
                <%if f.object.id.present? %>
        <div class="col-md-2 col-xs-6 pull-right">
            <%=link_to "Imprimir", [@cliente, :print],  :class => "btn btn-block btn-default btn-flat", :target => '_blank'%>
        </div>
    <% end %>
</div>
<% end %>

app/views/clientes/_sidebar.erb
<div class="col-md-3">
    <div class="margin-bottom">
<%= link_to 'Adicionar', new_cliente_path, :class => 'btn btn-block btn-success btn-flat' %>
  </div>
<%= form_tag clientes_path, :id => "filter_form", :class => "filter_form", :method => 'get' do %>   
    
   <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Cliente</h3>
    </div>
    <div class="box-body">
        <div class="col-md-12 margin-bottom">                    
    <%= text_field_tag :search_with, params[:search_with], :class => 'form-control  input-sm', :placeholder => "Buscar por cliente" %> 
      <span class="glyphicon glyphicon-search form-control-feedback"></span>   
        </div>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
    
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Status</h3>
    </div>
    <div class="box-body no-padding sidebar-scroll">
        <ul class="nav nav-pills nav-stacked">
            <% @status.each do |status| %>
             <li>
                <a href='#' onclick="SubmitFilter();return false;">              
                    <%= check_box_tag "status[]", status.id %>
                    <%= status.name %>
                 </a>
            </li>
            <% end %>
      </ul>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
      
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Vendedores</h3>
    </div>
    <div class="box-body no-padding sidebar-scroll">
      <form class="filter_form", method="get">
        <ul class="nav nav-pills nav-stacked">
            <% @vendedores.each do |vendedor| %>
             <li>
                <a href='#' onclick="SubmitFilter();return false;">
                    <%= check_box_tag("vendedor[]", vendedor.id) %>
                <%= vendedor.name %> </a>
            </li>
            <% end %>
      </ul>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Ramo de Mercado</h3>
    </div>
    <div class="box-body no-padding sidebar-scroll">
      <form class="filter_form", method="get">
        <ul class="nav nav-pills nav-stacked">
            <% @ramos.each do |ramo| %>
             <li>
                <a href='#' onclick="SubmitFilter();return false;">
                <%= check_box_tag("ramo[]", ramo.id) %>
                <%= ramo.name %> </a>
            </li>
            <% end %>
      </ul>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
<% end %>

    
</div>

app/views/clientes/edit.html.erb
<section class="content-header">
    <h1>Editar Cliente</h1>
</section>
<section class="content">
    <%= render 'form' %>
</section>

app/views/clientes/index.html.erb
<section class="content-header">
<h1>Clientes</h1>
</section>
<section class="content">
<%= render 'sidebar', cache: true%> 
    <div class="col-sm-9">
        <div id="clientes" class="filter_row">
        <%= render 'clientes', cache: true%>
        </div>
    </div>
</section>

app/views/clientes/index.js.erb
$('#clientes').html('<%= escape_javascript(render("clientes")) %>');  

app/views/clientes/new.html.erb
<section class="content-header">
    <h1>Novo Cliente</h1>
</section>
<section class="content">
    <%= render 'form' %>
</section>

app/views/clientes/print.html.erb
<!-- Main content -->
  <section class="invoice">
    <!-- title row -->
    <div class="row">
      <div class="col-xs-12">
        <h2 class="page-header">
          <i class="fa fa-globe"></i> Cardcom
          <small class="pull-right">Date: 2/10/2014</small>
        </h2>
      </div><!-- /.col -->
    </div>
    <!-- info row -->
    <div class="row invoice-info">
      <div class="col-sm-4 invoice-col">
        Empresa
        <address>
          <strong><%=@cliente.nome_fantasia%></strong><br>
          <%=@cliente.cnpj%><br>
           <%=@cliente.inscricao_municipal%><br>
           <%=@cliente.inscricao_estadual%><br/>
          Email: john.doe@example.com
        </address>
      </div><!-- /.col -->
      <div class="col-sm-4 invoice-col">
        <b>Cadastro #<%=@cliente.id%></b><br/>
        <br/>
        <b>Order ID:</b> 4F3S8J<br/>
        <b>Payment Due:</b> 2/22/2014<br/>
        <b>Account:</b> 968-34567
      </div><!-- /.col -->
    </div><!-- /.row -->

    <!-- Table row -->
    <div class="row">
      <div class="col-xs-12 table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Qty</th>
              <th>Product</th>
              <th>Serial #</th>
              <th>Description</th>
              <th>Subtotal</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Call of Duty</td>
              <td>455-981-221</td>
              <td>El snort testosterone trophy driving gloves handsome</td>
              <td>$64.50</td>
            </tr>
            <tr>
              <td>1</td>
              <td>Need for Speed IV</td>
              <td>247-925-726</td>
              <td>Wes Anderson umami biodiesel</td>
              <td>$50.00</td>
            </tr>
            <tr>
              <td>1</td>
              <td>Monsters DVD</td>
              <td>735-845-642</td>
              <td>Terry Richardson helvetica tousled street art master</td>
              <td>$10.70</td>
            </tr>
            <tr>
              <td>1</td>
              <td>Grown Ups Blue Ray</td>
              <td>422-568-642</td>
              <td>Tousled lomo letterpress</td>
              <td>$25.99</td>
            </tr>
          </tbody>
        </table>
      </div><!-- /.col -->
    </div><!-- /.row -->

    <div class="row">
      <!-- accepted payments column -->
      <div class="col-xs-6">
        <p class="lead">Payment Methods:</p>
        <img src="../../dist/img/credit/visa.png" alt="Visa"/>
        <img src="../../dist/img/credit/mastercard.png" alt="Mastercard"/>
        <img src="../../dist/img/credit/american-express.png" alt="American Express"/>
        <img src="../../dist/img/credit/paypal2.png" alt="Paypal"/>
        <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
          Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem plugg dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
        </p>
      </div><!-- /.col -->
      <div class="col-xs-6">
        <p class="lead">Amount Due 2/22/2014</p>
        <div class="table-responsive">
          <table class="table">
            <tr>
              <th style="width:50%">Subtotal:</th>
              <td>$250.30</td>
            </tr>
            <tr>
              <th>Tax (9.3%)</th>
              <td>$10.34</td>
            </tr>
            <tr>
              <th>Shipping:</th>
              <td>$5.80</td>
            </tr>
            <tr>
              <th>Total:</th>
              <td>$265.24</td>
            </tr>
          </table>
        </div>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </section><!-- /.content -->

app/views/clientes/show.html.erb
<p>
  <strong>Nome fantasia:</strong>
  <%= @cliente.nome_fantasia %>
</p>

<p>
  <strong>Razao social:</strong>
  <%= @cliente.razao_social %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @cliente.cnpj %>
</p>

<p>
  <strong>Inscrição Municipal:</strong>
  <%= @cliente.inscricao_municipal %>
</p>

<p>
  <strong>Inscrição Estadual:</strong>
  <%= @cliente.inscricao_estadual %>
</p>

<p>
  <strong>Tipo de Faturamento:</strong>
  <%= @cliente.cliente_faturamento.name if @cliente.cliente_faturamento%>
</p>

<p>
  <strong>Status:</strong>
  <%= @cliente.cliente_status.name if @cliente.cliente_status%>
</p>

<p>
  <strong>Vendedor:</strong>
  <%= @cliente.user.name if @cliente.user %>
</p>

<p>
  <strong>Observação:</strong>
  <%= @cliente.observacao %>
</p>