config/routes.rb
Rails.application.routes.draw do

  resources :ordem_producaos do
      get "1/update_produtos_op" => "ordem_producaos#update_produtos_op"
       get '/print/' => "print#ordem_producao_print"

            member do
            get :clone
        end
  end

    
  resources :layouts do
      member do
            get :clone
        end
      end
        
  resources :orcamentos do
      get '/print/' => "print#orcamento_print"
        member do
            get :clone
        end
  end
  resources :pedido_vendas do
      get '/print/' => "print#pedido_venda_print"
        member do
            get :clone
        end
  end
  resources :clientes do
      get '/print/' => "print#cliente_print"
  end
    
   resources :cliente_estoque_minimos

  ActiveAdmin.routes(self)
    devise_for :users
    devise_scope :user do
      authenticated :user do
        root "default#index", as: :authenticated_root
      end
      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end
    
    root 'devise/sessions#new'
    get 'activities/index'
    get "access_denied" => "default#access_denied"
    get "estado/:estado_id/cidades" => "default#update_cidades"
    get "produto/:produto_id/materials" => "default#update_produtos"
    get "estoque/:tipo_id/:cliente_id/:produto_id/materials" => "default#update_materials_op"
    get "cliente/enderecos" => "default#busca_endereco"
    
    get "cliente/:cliente_id/enderecos" => "default#busca_endereco_cliente"

    get "impressora/:impressora_id/configs" => "default#update_impressora_configs"
    get "gerar-venda/:orcamento_id" => "default#gerar_venda"
    get "gerar-op/:pedido_venda_id" => "default#gerar_op"
    get "/feed" => "activities#index", as: :feed
    get "orcamento-item-descricao/:descricao_id" => "default#update_item_descricao"
    
end

app/models/pedido_venda.rb
class PedidoVenda < ActiveRecord::Base

    attr_accessible :user_id, :id, :cliente_endereco_id, :cliente_id, :data_solicitacao, :detalhes,  :recibo, :nota_fiscal, :forma_pagamento_id, :pedido_venda_status_id, :pedido_venda_items_attributes
       
 include Filterable
    scope :status, -> (status) {
        statuses = status.split(',')
        where pedido_venda_status_id: statuses }
    
    scope :vendedor, -> (vendedor) {
        vendedores = vendedor.split(',')
        where user_id: vendedores }
    
    
    scope :cliente_name, lambda { |cliente_name|
  where('LOWER(clientes.nome_fantasia) LIKE ?', "%#{cliente_name}%").joins(:cliente) 
        }
    
    scope :search_with, lambda { |search|
        where('id LIKE ?', search) 

        }

      scope :solicitacao_start_date,  -> (start_date) {
        start_date = start_date.to_s.gsub('/','-')
        start_date = start_date.to_date.strftime("%Y-%m-%d")
        where("data_solicitacao >= ?", start_date)
      }

      scope :solicitacao_end_date,  -> (end_date) {
        end_date = end_date.to_s.gsub('/','-')
        end_date = end_date.to_date.strftime("%Y-%m-%d")
        where("data_solicitacao <= ?", end_date)
      }

    
    
    validates_presence_of :cliente_id, :user_id, :data_solicitacao, :pedido_venda_status_id

    
    belongs_to :user
    belongs_to :cliente
    belongs_to :pedido_venda_status
    belongs_to :forma_pagamento
    has_many :pedido_venda_items, :dependent => :destroy
 
    accepts_nested_attributes_for :pedido_venda_items, :reject_if => :all_blank, :allow_destroy => true

    
 include PublicActivity::Model
 tracked :owner => proc {|controller, model| controller.current_user}

     
  def calculate_totals
    pedido_venda_items.map do |i|
      i.subtotal
    end.sum
  end  

     
end

    


 

app/controllers/pedido_vendas_controller.rb
class PedidoVendasController < InheritedResources::Base
    load_and_authorize_resource  
    before_filter :authenticate_user!
       
        def index
        @status = PedidoVendaStatus.all  
         @vendedores = User.where(departamento_id: 1)
         @pedido_vendas  = PedidoVenda.includes(:user).filter(params.slice(:status,  :cliente_name, :vendedor, :search_with, :solicitacao_start_date, :solicitacao_end_date)).order("ID").paginate(:per_page => 50, :page => params[:page])

     end 
    
    def create  
        create! { collection_url }
        flash[:notice] = 'Pedido de venda salvo com sucesso!' 
    end
    
    def update  
        update! { edit_pedido_venda_path}
        flash[:notice] = 'Pedido de venda atualizado com sucesso!'

    end 
    
    def clone
        @pedido_venda_old = PedidoVenda.find(params[:id])
        @pedido_venda = @pedido_venda_old.dup
         @pedido_venda_old.pedido_venda_items.each do |pedido_venda|
            @pedido_venda.pedido_venda_items.new([
               :material_id => pedido_venda.material_id,
               :produto_id => pedido_venda.produto_id,
               :quantidade => pedido_venda.quantidade,
               :preco => pedido_venda.preco])
        end 
         render "new"
    end
    
    
    
  private
    def pedido_venda_params
      params.require(:pedido_venda).permit(:user_id, :cliente_id, :cliente_endereco_id, :data_solicitacao, :detalhes, :recibo, :nota_fiscal, :forma_pagamento_id, :pedido_venda_status_id,
          pedido_venda_items_attributes: [:id, :pedido_venda_id, :produto_id, :material_id, :valor, :desconto, :quantidade, :_destroy, :_update, :_create]) 
    end
    

end

 

       

app/helpers/pedido_vendas_helper.rb
module PedidoVendasHelper
end

app/views/pedido_vendas/_form.html.erb
<%= simple_form_for(@pedido_venda) do |f| %>
  <%= render "shared/messages", object: f.object %>

<div class="box box-success">
<div class="box-header">
        <div class="col-md-2 pull-left">
            <h3 class="no-margin box-title">Código: <%= f.object.id %></h3>
</div>
        
        
</div>
<div class="box-body">
        <div class="col-sm-6">
            <%= f.input :cliente_id,:collection =>  Cliente.where(cliente_status_id: 1),:label_method => :nome_fantasia,:value_method => :id,:label => "Cliente" ,:include_blank => true %>
        </div>
        <div class="col-sm-3">
             <%=f.input :data_solicitacao,  :as => :date_time, :label =>"Solicitado em", input_html: { :"data-inputmask" => "'alias': 'dd/mm/yyyy'",  :"data-mask"=>"" }%>
        </div>
        <div class="col-sm-3">  
        <%= f.input :user_id,:collection =>  User.where(departamento_id: 1),:label_method => :name,:value_method => :id,:label => "Vendedor" ,:include_blank => true %>
        </div>
        <div class="col-sm-3">
            <%=f.association :forma_pagamento, collection: FormaPagamento.where(active: true), :label => "Forma de pagamento",:include_blank => false %>
        </div>
        <div class="col-sm-3">
            <%=f.association :pedido_venda_status, collection: PedidoVendaStatus.where(active: true), :label => "Status",:include_blank => false %>
        </div>
        <div class="col-sm-2"  style="padding-top: 15px;">
            <%= f.input :recibo, :label =>"Emitir recibo" %>
        </div>
        <div class="col-sm-2"  style="padding-top: 15px;">
            <%= f.input :nota_fiscal, :label =>"Emitir nota fiscal"%>
        </div>
         <div class="col-sm-12">
            <%= f.input :detalhes,:as => :text,  :label =>"Detalhes"%>
        </div>
</div><!-- /.box-body -->
</div>

<div class="box box-success">
        <div class="box-header">
          <h3 class="box-title">Produtos</h3>
        </div>
        <div class="box-body">
        <fieldset id="pedido_venda_items">
            <%= f.simple_fields_for :pedido_venda_items do |builder| %>
            <%= render "pedido_venda_item_fields", :f => builder %>
            <% end %>
                <div class="col-sm-6">
                    <%= link_to_add_association '+', f, :pedido_venda_items, :class => "btn  btn-default btn-flat"   %>
                </div>
                <div class="col-sm-2 pull-right">
                     <%= f.input :calculate_totals, :as => :currency, :label => "Total", :disabled => true, input_html: { class: 'total',   id: 'total',  alt: "decimal", :value => (number_with_precision(f.object.calculate_totals, :precision => 2) || 0)} %>
                    </div>
        </fieldset>
        </div><!-- /.box-body -->
      </div>


<div class="actions-bar row">
    <div class="col-md-2 col-xs-6 pull-right">
            <%= f.submit "Salvar", class:"btn btn-block btn-success btn-flat", :onclick => 'SubmitAndRemoveMask()' %>
        </div>
        <%if f.object.id.present? %>
        <div class="col-md-2 col-xs-6 pull-right">
            <%=link_to "Gerar OP",{:controller => "default", :action => "gerar_op", :pedido_venda_id => @pedido_venda.id }, data: { confirm: 'Deseja gerar uma OP?' }, :class => "btn btn-block btn-default btn-flat"  %>
        </div>
    <div class="col-md-2 col-xs-6 pull-right">
            <%=link_to "Imprimir", [@pedido_venda, :print],  :class => "btn btn-block btn-default btn-flat", :target => '_blank'%>
        </div>
    <div class="col-md-2 col-xs-6 pull-right">
            <%=link_to "Duplicar", clone_pedido_venda_path(params[:id]),  :class => "btn btn-block btn-default btn-flat",  data: { confirm: 'Deseja duplicar este pedido de venda?' } %>
     <%end%>
</div>

<% end %>
  

app/views/pedido_vendas/_pedido_venda_item_fields.html.erb
<div class="nested-fields item">
<div class="col-md-12">    
<div class="pull-right">
<%= link_to_remove_association f  do%>
    <span >×</span>
<% end %>
</div>
</div>
        <div class="col-sm-2">
        <%= f.input :quantidade, input_html: { class: 'quantidade',  onkeyup: "SomarItens()" } %>
        </div>
        <div class="col-sm-3">
            <%var = "produto_" + (Random.rand(10...42)).to_s %>
             <%= f.input :produto_id, collection: Produto.where(active: true), input_html: { id: var, onchange: "DynamicSelect()"  }, :include_blank => false %>
        </div>
        <div class="col-sm-3">
            <%= f.input :material_id, collection: Material.where(active: true),input_html: { 
                         "data-option-dependent" => true,
                         "data-option-observed" => var,
                         "data-option-url" => "/produto/:produto_id:/materials.json",
                         "data-option-key-method" => :id,
                         "data-option-value-method" => :name } %>
         </div>        
        <div class="col-sm-2">
                    <%= f.input :preco, :as => :currency, :label => "Preço unitário", input_html: { class: 'valor',   onkeyup: "SomarItens()",  alt: "decimal", :value => (number_with_precision(f.object.preco, :precision => 2) || 0)} %>
        </div>
         <div class="col-sm-2">
        <%= f.input :subtotal, :as => :currency, :disabled => true, input_html: { class: 'subtotal',:value => (number_with_precision(f.object.subtotal, :precision => 2) || 0) } %> 
        </div>
    
</div>

app/views/pedido_vendas/_pedido_vendas.html.erb
<% if @pedido_vendas.size == 0 %>
   <div class="blank_slate_container">
              <span class="blank_slate">
                <span>Não há pedidos de vendas para serem exibidos</span><br/>
            <small><%=link_to "Clique aqui",  new_pedido_venda_path%> e crie um novo pedido de venda.</small>
              </span>
            </div> 
<% else %>
    <% @pedido_vendas.each do |pedido_venda| %>
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title"><small>Código:</small> <%= pedido_venda.id %> </h3>
                 <%if pedido_venda.pedido_venda_status_id == 2 %>
                <span class="pull-right label label-danger"><%= pedido_venda.pedido_venda_status.name if pedido_venda.pedido_venda_status %></span>
            <%else%>
                <span class="pull-right label label-success"><%= pedido_venda.pedido_venda_status.name if pedido_venda.pedido_venda_status %></span>
            <%end%>

            </div>
            <div class="box-body">
                <div class="col-sm-8">

                   <small>Cliente:</small> <%= pedido_venda.cliente.nome_fantasia %> <br/>
                  <small>Solicitado em:</small> <%= l(pedido_venda.data_solicitacao) if pedido_venda.data_solicitacao %> <br/>
                  <small>Vendedor:</small> <%= pedido_venda.user.name if pedido_venda.user %>  <br/>
                    <small>Produtos:
                <%pedido_venda.pedido_venda_items.each do |item| %> 
                            <%= item.produto.name if item.produto %> -
                            <%= item.material.name if item.material %>,
                    <%end%>
                 </small>
              </div>
                <div class="col-sm-2 ">
              <%= number_to_currency(pedido_venda.calculate_totals)  %>
                
                    </div>
                <div class="col-sm-2 no-padding ">
                      <%=link_to "Editar",  edit_pedido_venda_path(pedido_venda),  :class => "btn btn-block btn-success  btn-flat"%>
                
                    </div>




            </div><!-- /.box-body -->
        </div>
    <%end%>
<%end%>

app/views/pedido_vendas/_sidebar.erb
<div class="col-md-3 sidebar-filter">
    <div class="margin-bottom">
<%= link_to 'Adicionar', new_pedido_venda_path, :class => 'btn btn-block btn-success btn-flat margin-bottom' %>
  </div>
 
        
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Código</h3>
    </div>
    <div class="box-body">
        <div class="col-md-12 margin-bottom">    
                        
    <%= form_tag pedido_vendas_path, :id => "search", :method => 'get' do %>   
    <%= text_field_tag :search_with, params[:search_with], type: :number, :class => 'form-control  input-sm', :placeholder => "Buscar por código" %> 
      <span class="glyphicon glyphicon-search form-control-feedback"></span>
<% end %>  
            
</div>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
  
    
    
<%= form_tag pedido_vendas_path, :id => "filter_form", :class => "filter_form", :method => 'get' do %>   
    
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Cliente</h3>
    </div>
    <div class="box-body">
        <div class="col-md-12 margin-bottom">    
                        
    <%= text_field_tag :cliente_name, params[:cliente_name], :class => 'form-control  input-sm', :placeholder => "Buscar por cliente" %> 
      <span class="glyphicon glyphicon-search form-control-feedback"></span>
            
</div>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
  
    
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Data de Solicitação</h3>
    </div>
    <div class="box-body">
        <div class="col-md-12 margin-bottom">    
                        
             <div class="search_with_date">
            <%= text_field_tag :solicitacao_start_date, params[:solicitacao_start_date],   :class => 'form-control  datepicker input-sm date_time', :placeholder =>'De'  %>  
            <span>-</span>
        <%= text_field_tag :solicitacao_end_date, params[:solicitacao_end_date],   :class => 'form-control datepicker  input-sm date_time',:placeholder =>'Até' %> 
        </div>
            
</div>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
    

    
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Status</h3>
    </div>
    <div class="box-body  sidebar-scroll">
        <ul class="nav nav-pills nav-stacked">
            <% @status.each do |status| %>
             <li>
                <a href='#' onclick="SubmitFilter();return false;">              
                    <%= check_box_tag "status[]", status.id %>
                    <%= status.name %>
                 </a>
            </li>
            <% end %>

      </ul>

    </div><!-- /.box-body -->
  </div><!-- /. box -->
      
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Vendedores</h3>
    </div>
    <div class="box-body sidebar-scroll">
      <form class="filter_form", method="get">
        <ul class="nav nav-pills nav-stacked">
            <% @vendedores.each do |vendedor| %>
             <li>
                <a href='#' onclick="SubmitFilter();return false;">
                    <%= check_box_tag("vendedor[]", vendedor.id) %>
                <%= vendedor.name %> </a>
            </li>
            <% end %>
      </ul>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
          
    
<% end %>  
</div> 

app/views/pedido_vendas/edit.html.erb
<section class="content-header">
<h1>Editar Pedido de Venda</h1>
</section>
<section class="content">
    <%= render 'form' %>
</section>


  

app/views/pedido_vendas/index.html.erb
<section class="content-header">
<h1>Pedido de Vendas</h1>
</section>
<section class="content">
    <%= render 'sidebar', cache: true%> 
    <div class="col-sm-9">
        <div id="pedido_vendas"  class="filter_row">
        <%= render 'pedido_vendas', cache: true%>
        </div>
    </div>
</section>

app/views/pedido_vendas/index.js.erb
$('#pedido_vendas').html('<%= escape_javascript(render("pedido_vendas")) %>');  

app/views/pedido_vendas/new.html.erb
<section class="content-header">
<h1>Novo Pedido de Venda</h1>
</section>
<section class="content">
    <%= render 'form' %>
</section>


  

app/views/pedido_vendas/print.html.erb
    <!-- info row -->
    <div class="row invoice-info">
      <div class="col-sm-4 invoice-col">
        Empresa
        <address>
          <strong><%=@pedido_venda.cliente.nome_fantasia%></strong><br>
          Email: john.doe@example.com
        </address>
      </div><!-- /.col -->
      <div class="col-sm-4 invoice-col">
        <b>Cód. Pedido de Venda:</b> <%=@pedido_venda.id%><br/>
        <b>Data de Solicitação:</b> <%= l(@pedido_venda.data_solicitacao) if @pedido_venda.data_solicitacao %><br/>
        <b>Forma de Pagamento:</b> <%=@pedido_venda.forma_pagamento.name if @pedido_venda.forma_pagamento%><br/>
      </div><!-- /.col -->
      <div class="col-sm-4 invoice-col">
        <b>Vendedor:</b> <%=@pedido_venda.user.name if @pedido_venda.user%><br/>
        <b>Status:</b> <%=@pedido_venda.pedido_venda_status.name if @pedido_venda.pedido_venda_status%><br/>
          <%if @pedido_venda.recibo == true%>
          Emitir recibo<br/>
          <%end%>
          
          <%if @pedido_venda.nota_fiscal == true%>
          Emitir nota fiscal
          <%end%>
          
      </div><!-- /.col -->
    </div><!-- /.row -->

    <!-- Table row -->
    <div class="row">
      <div class="col-xs-12 table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Quantidade</th>
              <th>Produto</th>
              <th>Material</th>
              <th>Valor Unit.</th>
              <th>Subtotal</th>
            </tr>
          </thead>
          <tbody>
         <% @pedido_venda_items.each do |item| %>
            <tr>
              <td><%= item.quantidade%></td>
              <td><%= item.produto.name%></td>
              <td><%= item.material.name%></td>
            <td><%= number_to_currency(item.valor) %></td>
              <td><%= number_to_currency(item.subtotal) %></td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div><!-- /.col -->
    </div><!-- /.row -->

    <div class="row">
      <!-- accepted payments column -->
      <div class="col-xs-6">
        <p class="lead">Detalhes:</p>
        <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
            <%=@pedido_venda.detalhes%> 
        </p>
      </div><!-- /.col -->
        <div class="col-xs-6 pull-right">
        <div class="table-responsive">
          <table class="table">
            <tr>
              <th style="width:50%">Total:</th>
              <td><%= number_to_currency(@pedido_venda.calculate_totals) %></td>
            </tr>
        </table>
        </div>
      </div><!-- /.col -->
    </div><!-- /.row -->

app/views/pedido_vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @pedido_venda.user_id %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @pedido_venda.cliente_id %>
</p>

<p>
  <strong>Data solicitacao:</strong>
  <%= @pedido_venda.data_solicitacao %>
</p>

<p>
  <strong>Detalhes:</strong>
  <%= @pedido_venda.detalhes %>
</p>

<p>
  <strong>Recibo:</strong>
  <%= @pedido_venda.recibo %>
</p>

<p>
  <strong>Nota fiscal:</strong>
  <%= @pedido_venda.nota_fiscal %>
</p>

<p>
  <strong>Forma pagamento:</strong>
  <%= @pedido_venda.forma_pagamento_id %>
</p>

<p>
  <strong>Pedido venda status:</strong>
  <%= @pedido_venda.pedido_venda_status_id %>
</p>

<%= link_to 'Edit', edit_pedido_venda_path(@pedido_venda) %> |
<%= link_to 'Back', pedido_vendas_path %>