config/routes.rb
Rails.application.routes.draw do

  resources :ordem_producaos do
      get "1/update_produtos_op" => "ordem_producaos#update_produtos_op"
       get '/print/' => "print#ordem_producao_print"

            member do
            get :clone
        end
  end

    
  resources :layouts do
      member do
            get :clone
        end
      end
        
  resources :orcamentos do
      get '/print/' => "print#orcamento_print"
        member do
            get :clone
        end
  end
  resources :pedido_vendas do
      get '/print/' => "print#pedido_venda_print"
        member do
            get :clone
        end
  end
  resources :clientes do
      get '/print/' => "print#cliente_print"
  end
    
   resources :cliente_estoque_minimos

  ActiveAdmin.routes(self)
    devise_for :users
    devise_scope :user do
      authenticated :user do
        root "default#index", as: :authenticated_root
      end
      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end
    
    root 'devise/sessions#new'
    get 'activities/index'
    get "access_denied" => "default#access_denied"
    get "estado/:estado_id/cidades" => "default#update_cidades"
    get "produto/:produto_id/materials" => "default#update_produtos"
    get "estoque/:tipo_id/:cliente_id/:produto_id/materials" => "default#update_materials_op"
    get "cliente/enderecos" => "default#busca_endereco"
    
    get "cliente/:cliente_id/enderecos" => "default#busca_endereco_cliente"

    get "impressora/:impressora_id/configs" => "default#update_impressora_configs"
    get "gerar-venda/:orcamento_id" => "default#gerar_venda"
    get "gerar-op/:pedido_venda_id" => "default#gerar_op"
    get "/feed" => "activities#index", as: :feed
    get "orcamento-item-descricao/:descricao_id" => "default#update_item_descricao"
    
end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base
    attr_accessible :user_id, :cliente_id, :cliente_endereco_id, :id, :data_solicitacao, :data_aprovacao, :referencia, :condicoes, :orcamento_status_id,  :orcamento_items_attributes, :orcamento_contatos_attributes
    
    include Filterable
    scope :status, -> (status) {
        statuses = status.split(',')
        where orcamento_status_id: statuses }
    
    scope :vendedor, -> (vendedor) {
        vendedores = vendedor.split(',')
        where user_id: vendedores }
    
    
    scope :cliente_name, lambda { |cliente_name|
  where('LOWER(clientes.nome_fantasia) LIKE ?', "%#{cliente_name}%").joins(:cliente) 
        }
    
    scope :search_with, lambda { |search|
        where('id LIKE ?', search) 

        }

      scope :solicitacao_start_date,  -> (start_date) {
        start_date = start_date.to_s.gsub('/','-')
        start_date = start_date.to_date.strftime("%Y-%m-%d")
        where("data_solicitacao >= ?", start_date)
      }

      scope :solicitacao_end_date,  -> (end_date) {
        end_date = end_date.to_s.gsub('/','-')
        end_date = end_date.to_date.strftime("%Y-%m-%d")
        where("data_solicitacao <= ?", end_date)
      }
    
  scope :aprovacao_start_date,  -> (start_date) {
        start_date = start_date.to_s.gsub('/','-')
        start_date = start_date.to_date.strftime("%Y-%m-%d")
        where("data_aprovacao >= ?", start_date)
      }
    
      scope :aprovacao_end_date,  -> (end_date) {
        end_date = end_date.to_s.gsub('/','-')
        end_date = end_date.to_date.strftime("%Y-%m-%d")
        where("data_aprovacao <= ?", end_date)
      }
    
    
    validates_presence_of :cliente_id, :user_id, :data_solicitacao, :orcamento_status_id

    belongs_to :user
    belongs_to :cliente
     belongs_to :cliente_endereco
    belongs_to :orcamento_status
    has_many :orcamento_items, :dependent => :destroy
    has_many :orcamento_contatos, :dependent => :destroy
 
    accepts_nested_attributes_for :orcamento_items, :reject_if => :all_blank, :allow_destroy => true
    accepts_nested_attributes_for :orcamento_contatos, :reject_if => :all_blank, :allow_destroy => true

    
 include PublicActivity::Model
 tracked :owner => proc {|controller, model| controller.current_user}


     def calculate_totals
        orcamento_items.map do |i|
            i.subtotal
        end.sum  
    end
     

     
end

 

app/controllers/orcamentos_controller.rb
class OrcamentosController < InheritedResources::Base
    load_and_authorize_resource  
    before_filter :authenticate_user!
    
    def index
        @status = OrcamentoStatus.all  
         @vendedores = User.where(departamento_id: 1)
         @orcamentos  = Orcamento.includes(:user).filter(params.slice(:status, :cliente_name, :vendedor, :search_with, :solicitacao_start_date, :solicitacao_end_date,:aprovacao_start_date, :aprovacao_end_date)).order("ID").paginate(:per_page => 50, :page => params[:page])

     end 
    
    
    def create  
        create! { collection_url } 
        flash[:notice] = 'Orçamento salvo com sucesso!' 
    end
    
    def update  
        update! { edit_orcamento_path}  
        flash[:notice] = 'Orçamento atualizado com sucesso!' 
    end
    
    def clone
        @orcamento_old = Orcamento.find(params[:id])
        @orcamento = @orcamento_old.dup
         @orcamento_old.orcamento_items.each do |orcamento_item|
            @orcamento.orcamento_items.new([
               :material_id => orcamento_item.material_id,
               :produto_id => orcamento_item.produto_id,
               :quantidade => orcamento_item.quantidade,
               :preco => orcamento_item.preco,
                :descricao => orcamento_item.descricao])
        end 
         render "new"
    end
    
  private

    def orcamento_params
      params.require(:orcamento).permit(:user_id, :cliente_id, :cliente_endereco_id, :data_solicitacao, :data_aprovacao, :referencia, :condicoes, :orcamento_status_id,:cliente_endereco_id,
        orcamento_items_attributes: [:id, :orcamento_id, :produto_id, :material_id, :preco, :desconto, :quantidade, :descricao, :active, :_destroy],
        orcamento_contatos_attributes: [:id, :orcamento_id, :data_contato, :descricao, :_destroy])
    end
    

end

app/helpers/orcamentos_helper.rb
module OrcamentosHelper
end

app/views/orcamentos/_form.html.erb
    <%= simple_form_for(@orcamento) do |f| %>
  <%= render "shared/messages", object: f.object %>
<div class="box box-success">
<div class="box-header">
        <div class="col-md-2 pull-left">
            <h3 class="no-margin box-title">Código:<%= f.object.id %></h3>
</div>
        
</div>
<div class="box-body">
        <div class="col-sm-6">
            <%= f.input :cliente_id,:collection =>  Cliente.where(cliente_status_id: 1),:label_method => :nome_fantasia,:value_method => :id,:label => "Cliente" ,:include_blank => true,  :required => true, input_html: {:onchange => 'DynamicSelectEnderecoCliente()' } %>         
        </div>
        <div class="col-sm-3">
             <%=f.input :data_solicitacao,  :required => true, :as => :date_time, :label =>"Solicitado em", input_html: { }%>
        </div>
    <div class="col-sm-3">
             <%=f.input :data_aprovacao, :as => :date_time, :label =>"Aprovado em" %>
        </div>
        <div class="col-sm-12">
            <div class="form-group text optional endereco">
                <label class="text optional control-label">Endereço</label><%= link_to ' (Alterar endereço) ', "#",  :onclick => "OpenModalEnderecoCliente();return false;" %> 
                <%= text_area_tag 'endereco', nil, class: 'text optional form-control endereco_cliente', disabled: true %>
            </div>
        </div>
        <div class="col-sm-3">  
        <%= f.input :user_id,:collection =>  User.where(departamento_id: 1),:label_method => :name,:value_method => :id,:label => "Vendedor" ,:include_blank => true, :required => true %>
        </div>
        <div class="col-sm-3">
            <%=f.association :orcamento_status, collection: OrcamentoStatus.where(active: true), :label => "Status",:include_blank => false %>
        </div>
          <div class="col-sm-6">
            <%= f.input :referencia, :label =>"Referência"%>
        </div>
         <div class="col-sm-12">
         <label class="text optional control-label">Condições Gerais</label><%= link_to ' (Inserir padrão) ', "#", :onclick => "InserirOrcamentoCondicoesGerais();return false;" %> 
            <%= f.input :condicoes,:as => :text,  :label => false%>
        </div>
</div><!-- /.box-body -->
</div>
<div class="box box-success">
        <div class="box-header">
          <h3 class="box-title">Produtos</h3>
        </div>
        <div class="box-body">
        <fieldset id="orcamento_items">
            <%= f.simple_fields_for :orcamento_items do |builder| %>
            <%= render "orcamento_item_fields", :f => builder %>
            <% end %>
                <div class="col-sm-6">
                    <%= link_to_add_association '+', f, :orcamento_items, :class => "btn  btn-default btn-flat", :style => 'margin-top: 20px'   %>
                </div>
                    <div class="col-sm-2 pull-right">
                                        <%= f.input :calculate_totals, :as => :currency, :label => "Total", :disabled => true, input_html: { class: 'total',   id: 'total',  alt: "decimal", :value => (number_with_precision(f.object.calculate_totals, :precision => 2) || 0)} %>
                    </div>
        </fieldset>
        </div><!-- /.box-body -->
      </div>

    <div id="endereco-cliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span></button>
        <h4 class="modal-title">Endereço do cliente</h4>
      </div>
      <div class="modal-body">
          <div class="col-sm-6">     
        <%= f.input :cliente_endereco_id,:collection =>  ClienteEndereco.where('cliente_id =?', f.object.cliente_id) || [] ,:label_method => :name,:value_method => :id,:label => "Endereços cadastrados" ,:include_blank => true, input_html: { :onchange => 'DynamicSelectEnderecoCompleto()',
                        class: 'endereco_id',
                         "data-option-dependent" => true,
                         "data-option-observed" => 'orcamento_cliente_id',
                         "data-option-url" => "/cliente/:cliente_id:/enderecos.json",
                         "data-option-key-method" => :id,
                         "data-option-value-method" => :name } %>
              

              
          </div>
          <div class="col-sm-12 ">
             <div class="form-group text optional endereco">
                <%=text_area(:endereco, :text, cols: 1, rows: 3, class: 'text optional form-control endereco_cliente', :disabled => true)%>
            </div>

          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default  btn-flat pull-left" onclick="CloseModal()">Cancelar</button>
        <button type="button" class="btn btn-success btn-flat" onclick="CloseModal()">Inserir</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="actions-bar row">
        <div class="col-md-2 col-xs-6 pull-right">
            <%= f.submit "Salvar", class:"btn btn-block btn-success btn-flat", :onclick => 'SubmitAndRemoveMask()' %>
        </div>
        <%if f.object.id.present? %>
        <div class="col-md-2 col-xs-6 pull-right">
            <%=link_to "Gerar venda",{:controller => "default", :action => "gerar_venda", :orcamento_id => @orcamento.id }, data: { confirm: 'Deseja gerar um pedido de venda?' }, :class => "btn btn-block btn-default btn-flat"  %>
        </div>
    <div class="col-md-2 col-xs-6 pull-right">
            <%=link_to "Imprimir", [@orcamento, :print],  :class => "btn btn-block btn-default btn-flat", :target => '_blank'%>
        </div>
       <div class="col-md-2 col-xs-6 pull-right">
            <%=link_to "Duplicar", clone_orcamento_path(params[:id]),  :class => "btn btn-block btn-default btn-flat",  data: { confirm: 'Deseja duplicar este orçamento?' } %>
        </div>
     <%end%>
</div>
<% end %>
  

app/views/orcamentos/_orcamento_item_fields.html.erb
<div class="nested-fields item">
<div class="col-md-12"> 

<div class="pull-right">
<%= link_to_remove_association f, onclick: 'RemoverSomarItens()'  do%>
    <i class="fa fa-minus"></i>
<% end %>
</div>
</div>
<div class="col-sm-2">
        <%= f.input :quantidade, input_html: { class: 'quantidade',  onkeyup: "SomarItens()" } %>
    </div>
    <div class="col-sm-3">
        <%var = "produto_" + (Random.rand(10...42)).to_s %>
         <%= f.input :produto_id, collection: Produto.where(active: true), input_html: { id: var, onchange: "DynamicSelect()"  }, :include_blank => false %>
    </div>
    <div class="col-sm-3">
        <%= f.input :material_id, collection: Material.where(active: true),input_html: { 
                     "data-option-dependent" => true,
                     "data-option-observed" => var,
                     "data-option-url" => "/produto/:produto_id:/materials.json",
                     "data-option-key-method" => :id,
                     "data-option-value-method" => :name } %>
     </div>        
    <div class="col-sm-2">
        <%= f.input :preco, :as => :currency, :label => "Preço unitário", input_html: { class: 'valor',   onkeyup: "SomarItens()",  alt: "decimal", :value => (number_with_precision(f.object.preco, :precision => 2) || 0)} %>
        
       
    </div>
     <div class="col-sm-2">
    <%= f.input :subtotal, :as => :currency, :disabled => true, input_html: { class: 'subtotal',:value => (number_with_precision(f.object.subtotal, :precision => 2) || 0) } %> 
    </div>
    <div class="col-sm-12">
    <label class="text optional control-label">Descrição</label><%= link_to ' (Usar modelo) ', "#", :onclick => "OpenModal();return false;" %>
    <%= f.text_area :descricao, :class => 'text optional form-control descricao_item' %> 
    </div>
    <div class="col-sm-12">
        <div class="pull-left">
        <%= f.input :active, :label => 'Este item deve ser somado ao total do orçamento.' %>
    </div>
        </div>

    <div class="modal fade descricao-items">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span></button>
        <h4 class="modal-title">Descrições de Produtos</h4>
      </div>
      <div class="modal-body">
          <div class="col-sm-6 margin-bottom">     
              <%= select_tag( :descricao_id, options_from_collection_for_select(OrcamentoItemDescricao.where('id > 1'), "id", "name"), class: "select form-control", :include_blank => true, onchange: "DynamicSelectDescricao()")%>          
          </div>
          <div class="col-sm-12 margin-bottom">
                <%=text_area(:descricao, :text, cols: 1, rows: 3, class: 'text optional form-control descricao_text',                         
                    "data-option-dependent" => true,
                     "data-option-observed" => "descricao_id",
                     "data-option-url" => "/orcamento-item-descricao/:descricao_id:.json",
                     "data-option-key-method" => :id,
                     "data-option-value-method" => :descricao)%>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default  btn-flat pull-left" onclick="CloseModal()">Cancelar</button>
        <button type="button" class="btn btn-success btn-flat" onclick="InserirDescricao()">Inserir</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
  
</div>
 

app/views/orcamentos/_orcamentos.html.erb
<% if @orcamentos.size == 0 %>
   <div class="blank_slate_container">
              <span class="blank_slate">
                <span>Não há orçamentos para serem exibidos</span><br/>
            <small><%=link_to "Clique aqui",  new_orcamento_path%> e crie um novo orçamento.</small>
              </span>
            </div> 
<% else %>
    <% @orcamentos.each do |orcamento| %>
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title"><small>Código:</small> <%= orcamento.id %> </h3>
            <%if orcamento.orcamento_status_id == 2 || orcamento.orcamento_status_id == 5  %>
                <span class="pull-right label label-danger"><%= orcamento.orcamento_status.name if orcamento.orcamento_status %></span>
                
            <%elsif orcamento.orcamento_status_id == 6%>
            <span class="pull-right label label-warning"><%= orcamento.orcamento_status.name if orcamento.orcamento_status %></span>

            <%elsif orcamento.orcamento_status_id == 1%>
                <span class="pull-right label label-success"><%= orcamento.orcamento_status.name if orcamento.orcamento_status %></span>
            
               <%else%>
            <span class="pull-right label label-primary"><%= orcamento.orcamento_status.name if orcamento.orcamento_status %></span>
            <%end%>


            </div>
            <div class="box-body">
                <div class="col-sm-8">

                   <small>Cliente:</small> <%= orcamento.cliente.nome_fantasia %> <br/>
                  <small>Solicitado em:</small> <%= l(orcamento.data_solicitacao) if orcamento.data_solicitacao %>  - 
                    <small>Aprovado em:</small> <%= l(orcamento.data_aprovacao) if orcamento.data_aprovacao %> <br/>
                  <small>Vendedor:</small> <%= orcamento.user.name if orcamento.user %>  <br/>
                    <small>Produtos:
                <%orcamento.orcamento_items.each do |item| %> 
                            <%= item.produto.name if item.produto %> -
                            <%= item.material.name if item.material %>,
                    <%end%>
                 </small>
              </div>
                <div class="col-sm-2 ">
              <%= number_to_currency(orcamento.calculate_totals)  %>
                
                    </div>
                <div class="col-sm-2 no-padding ">
                      <%=link_to "Editar",  edit_orcamento_path(orcamento),  :class => "btn btn-block btn-success btn-flat"%>
                
                    </div>




            </div><!-- /.box-body -->
        </div>
    <%end%>
<%end%>

app/views/orcamentos/_sidebar.erb
<div class="col-md-3 sidebar-filter">
    <div class="margin-bottom">
<%= link_to 'Adicionar', new_orcamento_path, :class => 'btn btn-block btn-success btn-flat margin-bottom' %>
  </div>
 
        
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Código</h3>
    </div>
    <div class="box-body">
        <div class="col-md-12 margin-bottom">    
                        
    <%= form_tag orcamentos_path, :id => "search", :method => 'get' do %>   
    <%= text_field_tag :search_with, params[:search_with], type: :number, :class => 'form-control  input-sm', :placeholder => "Buscar por código" %> 
      <span class="glyphicon glyphicon-search form-control-feedback"></span>
<% end %>  
            
</div>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
  
    
    
<%= form_tag orcamentos_path, :id => "filter_form", :class => "filter_form", :method => 'get' do %>   
    
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Cliente</h3>
    </div>
    <div class="box-body">
        <div class="col-md-12 margin-bottom">    
                        
    <%= text_field_tag :cliente_name, params[:cliente_name], :class => 'form-control  input-sm', :placeholder => "Buscar por cliente" %> 
      <span class="glyphicon glyphicon-search form-control-feedback"></span>
            
</div>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
  
    
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Data de Solicitação</h3>
    </div>
    <div class="box-body">
        <div class="col-md-12 margin-bottom">    
                        
             <div class="search_with_date">
            <%= text_field_tag :solicitacao_start_date, params[:solicitacao_start_date],   :class => 'form-control  datepicker input-sm date_time', :placeholder =>'De'  %>  
            <span>-</span>
        <%= text_field_tag :solicitacao_end_date, params[:solicitacao_end_date],   :class => 'form-control datepicker  input-sm date_time',:placeholder =>'Até' %> 
        </div>
            
</div>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
  
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Data de Aprovação</h3>
    </div>
    <div class="box-body">
        <div class="col-md-12 margin-bottom">    
                        
             <div class="search_with_date">
            <%= text_field_tag :aprovacao_start_date, params[:aprovacao_start_date],   :class => 'form-control  datepicker input-sm date_time', :placeholder =>'De' %>  
            <span>-</span>
        <%= text_field_tag :aprovacao_end_date, params[:aprovacao_end_date],   :class => 'form-control datepicker  input-sm date_time',:placeholder =>'Até' %> 
        </div>
            
</div>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
  

    
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Status</h3>
    </div>
    <div class="box-body  sidebar-scroll">
        <ul class="nav nav-pills nav-stacked">
            <% @status.each do |status| %>
             <li>
                <a href='#' onclick="SubmitFilter();return false;">              
                    <%= check_box_tag "status[]", status.id %>
                    <%= status.name %>
                 </a>
            </li>
            <% end %>

      </ul>

    </div><!-- /.box-body -->
  </div><!-- /. box -->
      
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Vendedores</h3>
    </div>
    <div class="box-body sidebar-scroll">
      <form class="filter_form", method="get">
        <ul class="nav nav-pills nav-stacked">
            <% @vendedores.each do |vendedor| %>
             <li>
                <a href='#' onclick="SubmitFilter();return false;">
                    <%= check_box_tag("vendedor[]", vendedor.id) %>
                <%= vendedor.name %> </a>
            </li>
            <% end %>
      </ul>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
          
    
<% end %>  
</div> 

app/views/orcamentos/edit.html.erb
<section class="content-header">
<h1>Editar Orçamento</h1>
</section>
<section class="content">
    <%= render 'form' %>
</section>


  

app/views/orcamentos/index.html.erb
<section class="content-header">
<h1>Orçamentos</h1>
</section>
<section class="content">
    <%= render 'sidebar', cache: true%> 
    <div class="col-sm-9">
        <div id="orcamentos" class="filter_row">
            <%= render 'orcamentos', cache: true%>
        </div>
    </div>
</section>

app/views/orcamentos/index.js.erb
$('#orcamentos').html('<%= escape_javascript(render("orcamentos")) %>');  

app/views/orcamentos/new.html.erb
<section class="content-header">
<h1>Novo Orçamento</h1>
</section>
<section class="content">
    <%= render 'form' %>
</section>

app/views/orcamentos/print.html.erb
<!-- info row -->
<div class="row invoice-info">
  <div class="col-sm-4 invoice-col">
    <address>
      <%=@orcamento.cliente.nome_fantasia%><br>
        <%= @orcamento.cliente_endereco.rua.to_s + " - " +
            @orcamento.cliente_endereco.numero.to_s  + " - " +
            @orcamento.cliente_endereco.complemento.to_s  + " - " +
            @orcamento.cliente_endereco.bairro.to_s  + " - " +
            @orcamento.cliente_endereco.cidade.name.to_s   + "/" +
            @orcamento.cliente_endereco.estado.uf.to_s    + " - " +
            @orcamento.cliente_endereco.cep.to_s 
            %>
    </address>
  </div><!-- /.col -->
  <div class="col-sm-4 invoice-col">
    <b>Cód. Orçamento:</b> <%=@orcamento.id%><br/>
    <b>Data de Solicitação:</b> <%= l(@orcamento.data_solicitacao) if @orcamento.data_solicitacao %><br/>
    <b>Vendedor:</b> <%=@orcamento.user.name if @orcamento.user%><br/>
  </div><!-- /.col -->
  <div class="col-sm-4 invoice-col"> 
  </div><!-- /.col -->
</div><!-- /.row -->
<div class="row">
    <div class="col-xs-12 text-center margin-bottom">
        <%=@orcamento.referencia%>
    </div>
</div>
<!-- Table row -->
<div class="row">
  <div class="col-xs-12 table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Quantidade</th>
          <th>Produto</th>
          <th>Material</th>
          <th>Valor Unit.</th>
          <th>Subtotal</th>
        </tr>
      </thead>
      <tbody>
     <% @orcamento_items.each do |item| %>
        <tr>
          <td><%= item.quantidade%></td>
          <td><%= item.produto.name if item.produto %></td>
          <td><%= item.material.name if item.material%></td>
        <td><%= number_to_currency(item.preco) %></td>
          <td><%= number_to_currency(item.subtotal) %></td>
        </tr>
          <tr> 
              <td colspan="5" style="border-top: none;"><%= item.descricao %></td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div><!-- /.col -->
</div><!-- /.row -->
<div class="row">
  <!-- accepted payments column -->
    <div class="col-xs-4 pull-right">
    <div class="table-responsive">
      <table class="table">
        <tr>
          <th >Total:</th>
          <td><%= number_to_currency(@orcamento.calculate_totals) %></td>
        </tr>
    </table>
    </div>
  </div><!-- /.col -->
    <div class="col-xs-12">
    <p class="lead">Condiçoes Gerais:</p>
    <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
        <%=@orcamento.condicoes%> 
    </p>
  </div><!-- /.col -->
</div><!-- /.row -->

app/views/orcamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @orcamento.user_id %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @orcamento.cliente_id %>
</p>

<p>
  <strong>Data solicitacao:</strong>
  <%= @orcamento.data_solicitacao %>
</p>

<p>
  <strong>Data aprovacao:</strong>
  <%= @orcamento.data_aprovacao %>
</p>

<p>
  <strong>Referencia:</strong>
  <%= @orcamento.referencia %>
</p>

<p>
  <strong>Condicoes:</strong>
  <%= @orcamento.condicoes %>
</p>

<p>
  <strong>Orcamento status:</strong>
  <%= @orcamento.orcamento_status_id %>
</p>

<%= link_to 'Edit', edit_orcamento_path(@orcamento) %> |
<%= link_to 'Back', orcamentos_path %>