config/routes.rb
Rails.application.routes.draw do

  resources :ordem_producaos do
      get "1/update_produtos_op" => "ordem_producaos#update_produtos_op"
       get '/print/' => "print#ordem_producao_print"

            member do
            get :clone
        end
  end

    
  resources :layouts do
      member do
            get :clone
        end
      end
        
  resources :orcamentos do
      get '/print/' => "print#orcamento_print"
        member do
            get :clone
        end
  end
  resources :pedido_vendas do
      get '/print/' => "print#pedido_venda_print"
        member do
            get :clone
        end
  end
  resources :clientes do
      get '/print/' => "print#cliente_print"
  end
    
   resources :cliente_estoque_minimos

  ActiveAdmin.routes(self)
    devise_for :users
    devise_scope :user do
      authenticated :user do
        root "default#index", as: :authenticated_root
      end
      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end
    
    root 'devise/sessions#new'
    get 'activities/index'
    get "access_denied" => "default#access_denied"
    get "estado/:estado_id/cidades" => "default#update_cidades"
    get "produto/:produto_id/materials" => "default#update_produtos"
    get "estoque/:tipo_id/:cliente_id/:produto_id/materials" => "default#update_materials_op"
    get "cliente/enderecos" => "default#busca_endereco"
    
    get "cliente/:cliente_id/enderecos" => "default#busca_endereco_cliente"

    get "impressora/:impressora_id/configs" => "default#update_impressora_configs"
    get "gerar-venda/:orcamento_id" => "default#gerar_venda"
    get "gerar-op/:pedido_venda_id" => "default#gerar_op"
    get "/feed" => "activities#index", as: :feed
    get "orcamento-item-descricao/:descricao_id" => "default#update_item_descricao"
    
end

app/views/shared/_activity.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-bell-o"></i>
    <span class="label label-warning"><%= PublicActivity::Activity.count%> </span>
</a>
    <ul class="dropdown-menu">
        <li class="header">Você tem <%= PublicActivity::Activity.count%> notificações</li>
        <li>

<div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto;">
    <ul class="menu" style=" width: 100%;">

    <% PublicActivity::Activity.order("created_at desc").each do |activity| %>  
<li>
    <h4> 
        <%= activity.owner.name if activity.owner %> 
        <small><i class="fa fa-clock-o"></i> <%= time_ago_in_words (activity.created_at)%></small>
    </h4>
    <%= render_activity activity %>
</li>
<% end %> 
        

</ul>
            </div>

            

</li>
<li class="footer"><%= link_to "Ver todas", :feed  %>

</li>
</ul>

app/views/shared/_footer.erb
<footer class="main-footer">

</footer>

app/views/shared/_messages.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Não foi possível salvar, há <%= pluralize(object.errors.count, "erro") %>  no formulário.
    </div>
  </div>
<% else %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-success alert-dismissable-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<% end %>

app/views/shared/_navigation.erb
<header class="main-header">
        <a href="/" class="logo">CApp</a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
   
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown  messages-menu">
                  <%= render 'shared/activity', cache: true%>              
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="hidden-xs"><%= current_user.name %></span>
                </a>
                <ul class="dropdown-menu">
                       <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                         <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'btn btn-default btn-flat' %> 
                      </div>
                    <div class="pull-right">
                      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-default btn-flat'  %>
                    </div>
                  </li>
                    
                </ul>
                  
              </li>
                
                        <%if current_user.has_role? :SuperAdmin%>            
        <li>
            <a href="/admin" target="_blank"><i class="fa fa-gears"></i></a>
            
        </li>
            <%end%> 
            </ul>
          </div>
        </nav>
      </header>

app/views/shared/_sidebar.erb
<aside class="main-sidebar">
    <section class="sidebar" style="height: auto;">
    <ul class="sidebar-menu">
        <li>
            <%= nav_link clientes_path,"<i class='fa fa-fw fa-user'></i> Clientes"  %>
            </li>
        <li>
            <%= nav_link orcamentos_path, "<i class='fa fa-fw fa-tag'></i> Orçamentos"%>
        </li>
        <li>      
            <%= nav_link pedido_vendas_path, "<i class='fa fa-fw fa-shopping-cart'></i> Pedidos de Vendas" %>
        </li>
        <li>
            <%= nav_link layouts_path, "<i class='fa fa-fw fa-pencil'></i> Layouts" %>
         </li>
        <li>
            <%= nav_link ordem_producaos_path, "<i class='fa fa-fw fa-file-text'></i> Ordens de Produção" %>
        </li>
    </ul>
    </section>
</aside>